### ISSUE TITLE
upgrading homestead causes call processing failures

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/homestead#325]
#### Symptoms

I'm running a system on release-82 and begin upgrading to release-94 starting with my first homestead node. After upgrading the first node I try a simple registration, but when the new homestead is part of the flow, sprout goes into a registration loop eventually exiting with a 483 (Too many hops).

I believe that this has something to do with the recent changes to sprout URI configuration because when comparing the old/new SAS traces I see scscf prefix in the UAA message for the server-name; where as the pre-upgrade UAA message does not contain the scscf prefix.

#### Impact

Stops call processing

#### Steps to reproduce
1) Launch system with two homesteads and sprouts on release-82
2) Upgrade a homestead node to release-94
3) Attempt registration
4) Fails when upgraded homestead is part of flow.

Note: My shared_config does not contain any URI configuration settings.

It should also be noted that the system works fine when all nodes are release-82 or release-94 (with the same shared_config), but not a mix of homesteads.

Diags from all nodes have been collected.

**Comment by eleanor-merry** [comment]
@dtheobald Can you try adding scscf.sprout.x.dat.core.clearwater.metaswitch.com to alias_list in shared_config?

**Comment by dtheobald** [comment]
It changed the behavior (i.e., no longer 483), but the registration fails on the UEs auth challenge response with a 480.

I've put two new SAS traces in the diags area. I'm not sure why there's two...

**Comment by JimBunch** [comment]
Marking as critical since the issue is call processing service affecting.

**Comment by eleanor-merry** [comment]
It looks like the HSS is rejecting the UAR - can you check your HSS setup on this? Can you also please send over updated debug logs as well?

**Comment by dtheobald** [comment]
I don't beleve that there's anything wrong with the HSS because the same scenario works when both homesteads are on either release-82 or release-94 and everything else being equal. It's only when the homestead versions are mixed that the error occurs.

I've put updated diags in the diags area. You'll also find a jpg containing the IPs of the SUT. If you want to take a look around, I'll leave it up overnight.

**Comment by mirw** [comment]
I took a quick look at this, but the diagnostics don't seem to match the behavior described above.  In particular, the diagnostics show a de-REGISTER (i.e. with Expires: 0), while the symptoms above describe a REGISTER.  The de-REGISTER causes Homestead to send a UAR with a User-Authorization-Type of DE_REGISTRATION.  The SAS trace shows the HSS responding with an Experimental-Result-Code of 5003 (DIAMETER_ERROR_IDENTITY_NOT_REGISTERED).  This is despite a search in SAS showing that the last message relating to this IMPI/IMPU was a successful Server-Assignment flow only a second earlier.

@eleanor-merry, I suspect it's worth you double-checking and see whether there's anything more we can get from this, but @dtheobald, I think we'll need sample flows from the working (i.e. same Homestead version) and failing (i.e. different Homestead versions) cases so that we can compare the messages being sent to the HSS, and hopefully understand why it's returning an error in one case and (presumably) not in the other.

**Comment by eleanor-merry** [comment]
I agree with your reading. Looking through the Sprout debug logs it looks like there's a successful register, then the 480 corresponds to a deregister. @dtheobald - can you please send us the flows from a working system as well?

**Comment by mirw** [comment]
@dtheobald, see my analysis in https://github.com/Metaswitch/sprout/issues/1394.  I think we should close this as a duplicate.

**Comment by dtheobald** [comment]
Yes, based on your analysis it would seem that this is a duplicate.
