### ISSUE TITLE
GR (split-brain) callee's state is set to "unregistered" in HSS after cache failure

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/homestead#345]
#### Symptoms

On a GR system where communications has been cut between sites, if a UE from one site calls a UE in the other site, the call fails appropriately but the callee's state in the HSS gets set to "unregistered" by homestead.

#### Impact

Once communications between the sites is restored, the callee can't receive any calls until it re-registers.

#### Release and environment 

release-94

#### Steps to reproduce
1, Start with two unregistered UEs (softphones)
2. Cut communications between geo sites
3. Register both UEs
4. Try calling for one site to the other
5. Call fails with a 480. However, if I look at the state of the “callee” in the HSS, has been changed from registered to unregistered (not to be confused with NOT-REGISTERED). 
6. Restore communications between the two sites.
7. Any attempt to call the “callee” (from either site) results in a 480 until the callee re-registers. This seems bad especially if the UEs re-registration time is 30 minutes, since this would mean that the user would be blissfully ignorant that he couldn’t receive a for that long. Note: The “callee” can make calls during this time.

A SAS trace for the call in step#5 is in the diags area.

If you look in that SAS trace, you’ll see that it’s homestead deciding to change the registration state to “unregistered”:
![p1](https://cloud.githubusercontent.com/assets/6430927/15044814/9fbcbc3c-129c-11e6-92d0-4b47c5a5fe16.png)
![p2](https://cloud.githubusercontent.com/assets/6430927/15044816/a2f30f3c-129c-11e6-822c-c13a664b63f1.png)

**Comment by mirw** [comment]
@rkd-msw, please can we discuss solutions when you're back in on Monday.

**Comment by rkd-msw** [comment]
@mirw - yes, grab me when you're free, probably this afternoon?

**Comment by mirw** [comment]
Thanks for discussing.  We've got a plan, but you're going to do some thinking on refining/sizing it.

**Comment by rkd-msw** [comment]
I was concerned that some upcoming work we're doing would affect this plan, but I no longer think that's the case.

We should do what we discussed - that is, deliberately setting a timestamp in the past when we write an UNREGISTERED state into Cassandra, so that when the clusters rejoin and we do the last-write-wins processing, the REGISTERED state will always win.

This should be cheap enough to do out of bugfix next sprint.

**Comment by rkd-msw** [comment]
The new plan, based on [discussion in the above PR](https://github.com/Metaswitch/homestead/pull/348#issuecomment-223232276), is to separate assignment and registration into separate columns. If, as a rule of thumb, we only set the registration column based on explicit user action, then when the sites rejoin, things that the user did (like registering or deregistering) will beat things the user didn't do (getting a call made to them).

There are six transitions:

Registered -> Not registered - this transition is due to explicit action (a REGISTER with expires=0), so you actively delete the row (affecting both columns)
Registered -> Unregistered - we don't currently support this transition, but if we did it would be due to an explicit unregister, so you actively delete the row (affecting both columns)
Unregistered -> Registered - this transition is due to explicit action (a REGISTER with expires > 0), so you set both the assignment and registration columns
Not registered -> Registered - same analysis as last point
Unregistered -> Not registered - I think you can only make this transition based on a Registration-Termination-Request, which is triggered by explicit action (either the operator hits a button or the user registers somewhere else), so we should delete the row (affecting both columns). If a user registered in site 1, and an RTR was subsequently sent to site 2, I think the right behaviour when the clusters rejoin is for them to not be registered.
Not registered -> Unregistered - this is the only one not based on explicit action - it's triggered by someone else making a call to the user - so here, we'll set the assigned column but leave the registration column untouched.

I'll implement that change and see if it works. If it doesn't, I've thought of another approach which might - storing per-site registration columns (is_registered_site1, is_registered_site2). Each site only writes to its local column, but takes the OR of all site's columns to determine if a user is registered (i.e. if any site thinks A is registered, all sites will treat A as registered).

**Comment by rkd-msw** [comment]
Actually, adding an assignment column doesn't seem to add any benefit and just complicates upgrade, so I'm going to try just the "leave the is_registered column as null" approach.

**Comment by rkd-msw** [comment]
#348 should have fixed this - can you retest when you pick up that fix?

**Comment by sathiyan-sivathas** [comment]
@rkd-msw tested the repro scenario for this bug under #348 so I think we should close this.
