### ISSUE TITLE
Homestead requires a DNS entry for localhost

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/homestead#386]
#### Symptoms
I spun up a split-network Homestead node. The Homestead process was unable to resolve localhost and so couldn't connect to Cassandra.

This works in a single network system because dnsmasq is installed in the management namespace and dnsmasq uses /etc/hosts/ which contains an entry for localhost. Similarly, this would work in a split network system where the signaling DNS server had an entry for localhost. Another work around is to set cassandra_hostname to be 127.0.0.1. However, these workarounds are not documented anywhere as far as I can tell, and it’s not at all clear to me that they’re the right thing to be doing.

#### Impact
Nothing worked.

#### Release and environment 
CC-homestead-10.0.0-20161116-~255.00.0.ova

#### Steps to reproduce
Spin up node

**Comment by sebrexmetaswitch** [comment]
It looks like this has been the case for ages, as we've always defaulted to "localhost" for the cassandra hostname (even before the ability to change it was added)

So we must have been relying on the DNS server to respond with 127.0.0.1 to a localhost query, which it seems most DNS servers do. Don't know if they're required to, but I suspect not.

We get away with this in other places (e.g. Sprout's chronos-hostname) because we use the IP address explicitly, like https://github.com/Metaswitch/sprout/blob/dev/src/main.cpp#L1908

Maybe the best fix here is to do something similar

**Comment by rkd-msw** [comment]
For the record, confirmed fixed in `10.0.0-161212-~255.00.0-161212.145405`.
