### ISSUE TITLE
homestead is not running

### ISSUE THREAD

**Issue by Ahmedeldeeb91** [Metaswitch/homestead#436]
I tried to install clearwater on 7 machines but when trying to register via zoiper a 403 forbidden response generated when checking nodes i found that homestead is not running i checked the log files and found that error in homestead_current.txt:
UTC Error main.cpp:756: Failed to initialize the Cassandra cache with error code 1.
UTC Status main.cpp:757: Homestead is shutting down
-----------------------------------------------------------------------------------------------------------------------------
when trying to follow procedures in that link http://clearwater.readthedocs.io/en/stable/Troubleshooting_and_Recovery.html to troubleshooting using cqlsh:
use homestead_provisioning;
use homestead_cache;
Error occured:
InvalidRequest: code=2200 [Invalid query] message="Keyspace 'homestead_provisioning' does not exist"
InvalidRequest: code=2200 [Invalid query] message="Keyspace 'homestead_cache' does not exist"
--------------------------------------------------------------------------------------------------------------------------------
so it seems that these two files arenot existing
could you send me this files !!?
Thanks in advance
[homestead_current.txt](https://github.com/Metaswitch/homestead/files/827910/homestead_current.txt)
[homestead_err.log.txt](https://github.com/Metaswitch/homestead/files/827922/homestead_err.log.txt)
[monit_status.log.txt](https://github.com/Metaswitch/homestead/files/827923/monit_status.log.txt)
[Terminal_log.txt](https://github.com/Metaswitch/homestead/files/827924/Terminal_log.txt)

**Comment by sebrexmetaswitch** [comment]
This is probably the same issue as you reported on the mailing list with your homer node. When installing the homestead node, did you only install the `homestead` package, rather than the `homestead-node` and `clearwater-prov-tools` packages?

You should be able to see if they're installed by running:
 
`dpkg -s homestead-node`
`dpkg -s clearwater-prov-tools`
 
If it’s not installed, you’ll have to install it by running:
 
`sudo DEBIAN_FRONTEND=noninteractive apt-get install homestead-node clearwater-prov-tools --yes`
 
Once you’ve done that, you will probably have to recreate the schemas manually by running:
 
`/usr/share/clearwater/cassandra-schemas/homestead_cache.sh`
`/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh`

**Comment by eleanor-merry** [comment]
Closing as answered.
